webtalk_init -webtalk_dir C:/Users/yosaf/Desktop/Sexto/Arquitectura/Proyecto/proyecto/proyecto.sim/sim_1/behav/xsim/xsim.dir/tb_ESCOMIPS_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 21 23:10:29 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "48a44f19-4d65-4777-949a-2ddba07c7f5d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "404f2fa3efe044f0a1e068c44bd2542b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "51" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6744_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2985132465 -regid "" -xml C:/Users/yosaf/Desktop/Sexto/Arquitectura/Proyecto/proyecto/proyecto.sim/sim_1/behav/xsim/xsim.dir/tb_ESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/yosaf/Desktop/Sexto/Arquitectura/Proyecto/proyecto/proyecto.sim/sim_1/behav/xsim/xsim.dir/tb_ESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/yosaf/Desktop/Sexto/Arquitectura/Proyecto/proyecto/proyecto.sim/sim_1/behav/xsim/xsim.dir/tb_ESCOMIPS_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
